//  Copyright (c) 2017, 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: rest-intro
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2017-09-19
:page-guide-category: microprofile
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to create a REST service with JAX-RS, JSON-P, and Open Liberty.
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE']
:page-related-guides: ['rest-client-java', 'rest-client-angularjs']
:page-permalink: /guides/{projectid}
:repo-description: Visit the https://openliberty.io/guides/{projectid}.html[website] for the rendered version of the guide.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Creating a RESTful web service

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to create a REST service with JAX-RS, JSON-B, and Open Liberty.

== What you'll learn

You will learn how to build and test a simple REST service with JAX-RS and JSON-B, which will expose
the JVM's system properties. The REST service will respond to `GET` requests made to the `\http://localhost:9080/LibertyProject/System/properties` URL.

The service responds to a `GET` request with a JSON representation of the system properties, where
each property is a field in a JSON object like this:

[source,json,role="no_copy"]
----
{
  "os.name":"Mac",
  "java.version": "1.8"
}
----

When you create a new REST application, the design of the API is important. The JAX-RS APIs could be
used to create JSON-RPC, or XML-RPC APIs, but it wouldn't be a RESTful service. A good RESTful service
is designed around the resources that are exposed, and on how to create, read, update, and delete the
resources.

The service responds to `GET` requests to the `/System/properties` path. The `GET` request should
return a `200 OK` response that contains all of the JVM's system properties.

[role="command"]
include::{common-includes}/gitclone.adoc[]

include::{common-includes}/trywhatyoubuild-beg.adoc[]

Check out the service at the
http://localhost:9080/LibertyProject/System/properties[^] URL. 

[role=command]
include::{common-includes}/trywhatyoubuild-end.adoc[]

== Creating a JAX-RS application

Navigate to the `start` directory to begin.

JAX-RS has two key concepts for creating REST APIs. The most obvious one is the resource itself, which is
modelled as a class. The second is a JAX-RS application, which groups all exposed resources under a
common path. You can think of the JAX-RS application as a wrapper for all of your resources.


[role="code_command hotspot" ,subs="quotes"]
----
#Create the `SystemApplication` class.#
`src/main/java/io/openliberty/guides/rest/SystemApplication.java`
----

The [hotspot=systemApplication]`SystemApplication` class extends the `Application` class, which in turn associates all JAX-RS
resource classes in the WAR file with this JAX-RS application, making them available under the common
path specified in the [hotspot=systemApplication]`SystemApplication` class. The [hotspot=applicationPath]`@ApplicationPath` annotation has a
value that indicates the path within the WAR that the JAX-RS application accepts requests from.

SystemApplication.java
[source, Java, linenums, role='code_column hide_tags=comment']
----
include::finish/src/main/java/io/openliberty/guides/rest/SystemApplication.java[]
----

== Creating the JAX-RS resource

In JAX-RS, a single class should represent a single resource, or a group of resources of the same type.
In this application, a resource might be a system property, or a set of system properties. It is easy
to have a single class handle multiple different resources, but keeping a clean separation between types
of resources helps with maintainability in the long run.

[role="code_command hotspot", subs="quotes"]
----
#Create the `PropertiesResource` class.#
`src/main/java/io/openliberty/guides/rest/PropertiesResource.java`
----

This resource class has quite a bit of code in it, so let's break it down into manageable chunks.

The [hotspot=path file=0]`@Path` annotation on the class indicates that this resource responds to the `properties` path
in the JAX-RS application. The [hotspot=applicationPath file=1]`@ApplicationPath` annotation in the [hotspot=systemApplication file=1]`SystemApplication` class together with
the [hotspot=path file=0]`@Path` annotation in this class indicates that the resource is available at the `System/properties`
path.

JAX-RS maps the HTTP methods on the URL to the methods on the class. The method to call is determined
by the annotations specified on the methods. In the application you are building, an HTTP `GET` request
to the `System/properties` path results in the system properties being returned.

The [hotspot=get file=0]`@GET` annotation on the method indicates that this method is to be called for the HTTP `GET`
method. The [hotspot=produces file=0]`@Produces` annotation indicates the format of the content that will be returned. The
value of the [hotspot=produces file=0]`@Produces` annotation will be specified in the HTTP `Content-Type` response header.
For this application, a JSON structure is to be returned. The desired `Content-Type` for a JSON
response is `application/json` with `MediaType.APPLICATION_JSON` instead of the `String` content type. Using a constant such as `MediaType.APPLICATION_JSON` is better because in the event of a spelling error, a compile failure occurs.

JAX-RS supports a number of ways to marshal JSON. The JAX-RS 2.1 specification mandates JSON-Binding
(JSON-B) and JAX-B. 

The method body returns the result of `System.getProperties()` which is of type `java.util.Properties`. Since the method 
is annotated with `@Produces(MediaType.APPLICATION_JSON)`, JAX-RS uses JSON-B to automatically convert the returned object
to JSON data in the HTTP response.

PropertiesResource.java
[source,java,linenums,role='code_column hide_tags=comment']
----
include::finish/src/main/java/io/openliberty/guides/rest/PropertiesResource.java[]
----

SystemApplication.java
[source,java,linenums,role='code_column hide_tags=comment']
----
include::finish/src/main/java/io/openliberty/guides/rest/SystemApplication.java[]
----

== Configuring the server

To get the service running, the Liberty server needs to be correctly configured.

[role="code_command hotspot", subs="quotes"]
----
#Create the server configuration file.#
`src/main/liberty/config/server.xml`
----

server.xml
[source,xml,linenums,role="code_column"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The configuration does the following actions:

. Configures the server to enable JAX-RS. This is specified in the [hotspot=featureManager file=0]`featureManager` element.
. Configures the server to resolve the HTTP port numbers from variables, which are then specified in
the Maven [hotspot file=1]`pom.xml` file. This is specified in the [hotspot=httpEndpoint file=0]`<httpEndpoint/>` element. Variables use the syntax `${variableName}`.
. Configures the server to run the produced Web application on a context root specified in the Maven
[hotspot file=1]`pom.xml` file. This is specified in the [hotspot=webApplication file=0]`<webApplication/>` element.

pom.xml
[source,xml,linenums,role="code_column"]
----
include::finish/pom.xml[]
----

The variables being used in the [hotspot file=0]`server.xml` file are provided by the [hotspot=bootstrap file=1]`<bootstrapProperties/>` section
of the Maven [hotspot file=1]`pom.xml`.

[role="command"]
include::{common-includes}/mvnbuild.adoc[]

Check out the service you created at the
http://localhost:9080/LibertyProject/System/properties[^] URL. 

When you are done checking out the services, stop the Open Liberty server by running the following command:
[role="command"]
```
mvn liberty:stop-server
```

== Testing the service

You could test this service manually by starting a server and pointing a web browser at the
http://localhost:9080/LibertyProject/System/properties[^] URL. Automated tests are a much better
approach because they will trigger a failure if a change introduces a bug. JUnit and the JAX-RS Client
API provide a very simple environment to test the application.

You can write tests for the individual units of code outside of a running application server, or they
can be written to call the application server directly. In this example, you will create a test that
does the latter.

[role="code_command hotspot", subs="quotes"]
----
#Create the `EndpointTest` class.#
`src/test/java/it/io/openliberty/guides/rest/EndpointTest.java`
----

EndpointTest.java
[source, Java, linenums, role="code_column hide_tags=comment"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[]
----

This test class has more lines of code than the resource implementation. This situation is common.
The test method is indicated with the [hotspot=test file=0]`@Test` annotation.

pom.xml
[source , xml, linenums,role="code_column"]
----
include::finish/pom.xml[]
----

The test code needs to know some information about the application in order to make requests. The server
port and the application context root are key, and are dictated by the server configuration. While this
information can be hardcoded, it is better to specify it in a single place like the Maven [hotspot file=1]`pom.xml`
file. Refer to the [hotspot file=1]`pom.xml` file to see how the application information such as the [hotspot=appname file=1]`<app.name/>`, [hotspot=httpport file=1]`<testServerHttpPort/>` and [hotspot=httpsport file=1]`<testServerHttpsPort/>` elements are provided in the file.

These Maven properties are then passed to the Java test program as the [hotspot=testsysprops file=1]`<systemPropertyVariables/>` element in
the [hotspot file=1]`pom.xml` file.

Getting the values to create a representation of the URL is simple. The test class uses the [hotspot=systemProperties file=0]`getProperty` method
to get the application details.

To call the JAX-RS service using the JAX-RS client, first create a `WebTarget` object by calling
the [hotspot=target file=0]`target` method providing the URL. To cause the HTTP request to occur [hotspot=requestget file=0]`request().get()` 
is invoked on the `WebTarget`. The [hotspot=requestget file=0]`get` method
call is a synchronous call that blocks until a response is received. This call returns a [hotspot=requestget file=0]`Response`
object, which can be inspected to determine whether the request was successful.

The first thing to check is that a `200` response was received. The JUnit [hotspot=assertequals file=0]`assertEquals` method can
be used for this.

Check the response body to ensure it returned the right information. Since the client and the server
are running on the same machine, it is reasonable to expect that the system properties for the local
and remote JVM would be the same. In this case, an assertion [hotspot=assertosname file=0]`assertEquals` is made that the `os.name` system property
for both JVMs is the same. You could write additional assertions to check for more values.

=== Running the tests

If the server is still running from the previous steps, stop it using the Maven `liberty:stop-server` goal from command line in the start directory:
[role="command"]
```
mvn liberty:stop-server
```

To rebuild, run the tests, and see that the test passes, run the Maven `install` command: 

[role='command']
```
mvn install
```

The Maven
build takes a little longer than before the test existed, but expect to see the following information
in the output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.rest.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.884 sec - in it.io.openliberty.guides.rest.EndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, add an assertion that you know fails, or change the existing
assertion to a constant value that doesn't match the `os.name` system property.

== Great work! You're done!

You developed a REST service in Open Liberty by using JAX-RS and JSON-P.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]
