//  Copyright (c) 2017 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: rest-intro
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2017-09-19
:page-guide-category: microprofile
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to create a REST service with JAX-RS, JSON-P, and Open Liberty.
:page-tags: ['REST', 'MicroProfile', 'microservices', 'Java EE']
:page-related-guides: ['rest-client-java', 'rest-client-angularjs']
:page-permalink: /guides/{projectid}
:repo-description: Visit the https://openliberty.io/guides/{projectid}.html[website] for the rendered version of the guide.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Creating a RESTful web service

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to create a REST service with JAX-RS, JSON-P, and Open Liberty.

== What you'll learn

You will learn how to build and test a simple REST service with JAX-RS and JSON-P, which will expose
the JVM's system properties. The REST service will respond to `GET` requests made to the URL:

[source,role="no_copy"]
----
http://localhost:9080/LibertyProject/System/properties
----

The service responds to a `GET` request with a JSON representation of the system properties, where
each property is a field in a JSON object like this:

[source,json,role="no_copy"]
----
{
  "os.name":"Mac",
  "java.version": "1.8"
}
----

When you create a new REST application, the design of the API is important. The JAX-RS APIs could be
used to create JSON-RPC, or XML-RPC APIs, but it wouldn't be a RESTful service. A good RESTful service
is designed around the resources that are exposed, and on how to create, read, update, and delete the
resources.

The service responds to `GET` requests to the `/System/properties` path. The `GET` request should
return a `200 OK` response that contains all of the JVM's system properties.

[role="command"]
include::{common-includes}/gitclone.adoc[]

== Creating a JAX-RS application

JAX-RS has two key concepts for creating REST APIs. The most obvious one is the resource itself, which is
modelled as a class. The second is a JAX-RS application, which groups all exposed resources under a
common path. You can think of the JAX-RS application as a wrapper for all of your resources. Having a
single JAX-RS application is common, although multiple are possible.

[role="code_command hotspot=7-9",subs="quotes"]
----
Create the `SystemApplication` class.
`src/main/java/io/openliberty/guides/rest/SystemApplication.java`
----

The [hotspot=7-9]`SystemApplication` class extends the `Application` class, which in turn associates all JAX-RS
resource classes in the WAR file with this JAX-RS application, making them available under the common
path specified in the [hotspot=7-9]`SystemApplication` class. The [hotspot=6]`@ApplicationPath` annotation has a
value that indicates the path within the WAR that the JAX-RS application accepts requests from.

SystemApplication.java
[source,java,linenums,role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/rest/SystemApplication.java[tags=**;!comment]
----

== Creating the JAX-RS resource

In JAX-RS, a single class should represent a single resource, or a group of resources of the same type.
In this application, a resource might be a system property, or a set of system properties. It is easy
to have a single class handle multiple different resources, but keeping a clean separation between types
of resources helps with maintainability in the long run.

[role="code_command hotspot=1-34", subs="quotes"]
----
Create the PropertiesResource class.
`src/main/java/io/openliberty/guides/rest/PropertiesResource.java`
----

This resource class has quite a bit of code in it, so let's break it down into manageable chunks.

The [hotspot=11]`@Path` annotation on the class indicates that this resource responds to the `properties` path
in the JAX-RS application. The `@ApplicationPath` annotation in the application class together with
the `@Path` annotation in this class indicates that the resource is available at the `System/properties`
path.

JAX-RS maps the HTTP methods on the URL to the methods on the class. The method to call is determined
by the annotations specified on the methods. In the application you are building, an HTTP [hotspot=14-34]`GET` request
to the `System/properties` path results in the system properties being returned.

The [hotspot=14]`@GET` annotation on the method indicates that this method is to be called for the HTTP `GET`
method. The [hotspot=15]`@Produces` annotation indicates the format of the content that will be returned, the
value of the `@Produces` annotation will be specified in the HTTP `Content-Type` response header.
For this application, a JSON structure is to be returned. The desired `Content-Type` for a JSON
response is `application/json` with `MediaType.APPLICATION_JSON` instead of the `String` content type. Using literal code such as `MediaType.APPLICATION_JSON` is better because in the event of a spelling error, a compile failure occurs.

JAX-RS supports a number of ways to marshal JSON. The JAX-RS specification mandates JSON-Processing
(JSON-P) and JAX-B. Most JAX-RS implementations also support a Java POJO-to-JSON conversion, which
allows the `Properties` object to be returned instead. Although this conversion would allow for a
simpler implementation, it limits code portability as POJO-to-JSON conversion is non-standard. This
gap in the specification is fixed in Java EE 8 with the inclusion of JSON-B.

The method body does the following actions:

. Creates a [hotspot=18]`JsonObjectBuilder` object using the `Json` class. The `JsonObjectBuilder` is then used
to populate a `JsonObject` with values.
. Calls the [hotspot=20]`getProperties` method on the `System` class to get a `Properties` object that contains
all the system properties.
. Calls the [hotspot=21]`entrySet` method on the `Properties` object to get a `Set` of all the entries.
. Convert the `Set` to a [hotspot=22]`Stream` (new in Java SE 8) by calling the `stream` method. Streams make
working through all the entries in a list very simple.
. Calls the [hotspot=23-24]`forEach` method on the `Stream` passing in a function that will be invoked for each
entry in the `Stream`. The function passed in will call the `add` method on the `JsonObjectBuilder`
for every entry in the stream. The key and value for the `JsonObject` will be obtained by calling
the `getKey` and `getValue` methods on the `Map.Entry` objects in the stream.
. Returns the [hotspot=26]`JsonObject` by calling the `build` method on the `JsonObjectBuilder`.

PropertiesResource.java
[source,java,linenums,role='code_column']
----
include::finish/src/main/java/io/openliberty/guides/rest/PropertiesResource.java[tags=**;!comment]
----

== Configuring the server

To get the service running, the Liberty server needs to be correctly configured.

[role="code_command hotspot=1-12", subs="quotes"]
----
Edit the file to update the placeholder text.
`src/main/liberty/config/server.xml`
----

Server.xml
[source,xml,linenums,role="code_column"]
----
include::finish/src/main/liberty/config/server.xml[]
----
The configuration does the following actions:

. Configures the server to support both JAX-RS 2.0 and JSON-P 1.0. This is specified in the [hotspot=3-6]`featureManager` element.
. Configures the server to pick up the HTTP port numbers from variables, which are then specified in
the Maven `pom.xml` file. This is specified in the [hotspot=8-9]`httpEndpoint` element. Variables use the syntax `${variableName}`.
. Configures the server to run the produced Web application on a context root specified in the Maven
`pom.xml` file. This is specified in the [hotspot=11]`webApplication` element.

The variables being used in the `server.xml` file are provided by the `bootstrapProperties` section
of the Maven `pom.xml`:

[source,xml,indent=0,role="no_copy"]
----
include::finish/pom.xml[tag=bootstrap]
----

[role="command"]
include::{common-includes}/mvnbuild.adoc[]

== Testing the service

You could test this service manually by starting a server and pointing a web browser at the
`\http://localhost:9080/LibertyProject/System/properties` URL. Automated tests are a much better
approach because they will trigger a failure if a change introduces a bug. JUnit and the JAX-RS Client
API provide a very simple environment to test the application.

You can write tests for the individual units of code outside of a running application server, or they
can be written to call the application server directly. In this example, you will create a test that
does the latter.

[role="code_command hotspot=1-43", subs="quotes"]
----
Create the test class file.
`src/test/java/it/io/openliberty/guides/rest/EndpointTest.java`
----

EndpointTest.java
[source,java,linenums,role="code_column"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=**;!comment]
----

This test class has more lines of code than the resource implementation. This situation is common.
The test method is indicated with the [hotspot=16]`@Test` annotation.

The test code needs to know some information about the application in order to make requests. The server
port and the application context root are key, and are dictated by the server configuration. While this
information can be hardcoded, it is better to specify it in a single place like the Maven `pom.xml`
file. Open the `pom.xml` file to see how the application information is provided in the file:

[source,xml,indent=0,role="no_copy"]
----
include::finish/pom.xml[tag=appdetails]
----

These Maven properties are then passed to the Java test program as a series of system properties in
the `pom.xml` file:

[source,xml,indent=0,role="no_copy"]
----
include::finish/pom.xml[tag=testsysprops]
----

Getting the values to create a representation of the URL is simple. The test class uses the [hotspot=18-20]`properties`
to get the application details.

The JAX-RS client can be used to make the REST call and convert the payload to and from a JSON-P
representation. To get the JAX-RS client to do the conversion, the client needs to have the [hotspot=23]`JsrJsonpProvider`
class registered with it by calling the `register` method and providing the `Class` object for the
`JsrJsonpProvider` class.

To call the JAX-RS service using the JAX-RS client, you first create a `WebTarget` object by calling
the `target` method providing the URL. To cause the HTTP request to occur first the `request` method
on `WebTarget` and then the `get` method on the returned object need to be called. The `get` method
call is a synchronous call that blocks until a response is received. This call returns a `Response`
object, which can be interrogated to determine whether the request was successful:

[source,java,indent=0,role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=request]
----

The first thing to check is that a `200` response was received. The JUnit `assertEquals` method can
be used for this. The first parameter is the error message that indicates why the test failed. The
second parameter is the expected response code, and the third is the actual response code. It is
important to associate the expected response code with the second parameter and the actual response
with the third parameter. Otherwise, the error messages from JUnit will claim that the actual response
is the expected one, which can cause confusion:

[source,java,indent=0,role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=response]
----

Check the response body to ensure it returned the right information. Since the client and the server
are running on the same machine, it is reasonable to expect that the system properties for the local
and remote JVM would be the same. In this case, an assertion is made that the `os.name` system property
for both JVMs is the same. You could write additional assertions to check for more values:

[source,java,indent=0,role="no_copy"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointTest.java[tags=body]
----

To rebuild, run the tests, and see that the test passes, run the command: `mvn install`. The Maven
build takes a little longer than before the test existed, but expect to see the following information
in the output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.rest.EndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.884 sec - in it.io.openliberty.guides.rest.EndpointTest

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, add an assertion that you know fails, or change the existing
assertion to a constant value that doesn't match the `os.name` system property.

include::https://raw.githubusercontent.com/OpenLiberty/guides-common/multipane/attribution.adoc[subs="attributes"]

== Great work! You're done!

You developed a REST service by using JAX-RS, JSON-P, and Liberty.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API]

include::https://raw.githubusercontent.com/OpenLiberty/guides-common/multipane/attribution.adoc[subs="attributes"]